services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - /home/hp/db_volume:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  app:
    image: node:20-alpine
    container_name: mgraphql-api
    working_dir: /app
    volumes:
      - /home/hp/Graphqlapi:/app
    ports:
      - "5000:3000"
    command: ["npm", "start", "--host", "0.0.0.0"]