services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - /home/hp/mongodb_vol:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  app:
    build: .
    ports:
      - 4700:4000
    environment:
      MONGO_URL: mongodb://mongo:27017/zapd
    depends_on:
      - mongo
volumes:
  mongo:{}